#!/bin/bash


if [ ! -z "$MARATHON_APP_ID" ]; then
    source /dev/shm/spandex.conf
fi


set -evx

SERVER_JAR="$SERVER_ROOT/$SERVER_ARTIFACT"

if [ ! -z "$MARATHON_APP_ID" ]; then
    /bin/env_parse /etc/${SERVER_CONFIG}.j2
fi

exec su socrata -c "exec /usr/bin/java \
     -Xmx${JAVA_XMX} \
     -Xms${JAVA_XMX} \
     ${CONFIG_LINE} \
     -Djava.net.preferIPv4Stack=true \
     -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
     -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
     -Dcom.sun.management.jmxremote.ssl=false \
     -Dcom.sun.management.jmxremote.authenticate=false \
     -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
     -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
     -XX:+ExitOnOutOfMemoryError \
     -jar $SERVER_JAR"
