#!/bin/sh

set -evx

SERVER_JAR="$SERVER_ROOT/$SERVER_ARTIFACT"

/bin/env_parse /etc/${SERVER_CONFIG}.j2

exec su socrata -c "exec /usr/bin/java \
     -Xmx${JAVA_XMX} \
     -Xms${JAVA_XMX} \
     -Dconfig.file=/etc/${SERVER_CONFIG} \
     -jar $SERVER_JAR"
