#!/bin/sh

set -ev

TILESERVER_JAR="$SERVER_ROOT/$SERVER_ARTIFACT"

/bin/env_parse ${SERVER_CONFIG}.j2
/bin/env_parse ${LOGBACK_CONFIG}.j2

exec /usr/bin/java \
    -Xmx${JAVA_MEM} \
    -Xms${JAVA_MEM} \
    -Dconfig.file=${SERVER_CONFIG} \
    -Dlogback.configurationFile=${LOGBACK_CONFIG} \
    -jar "$SERVER_JAR"
